export const TOKENS = {
  CLOCK: Symbol('CLOCK'),
  ID_GENERATOR: Symbol('ID_GENERATOR'),
  STORAGE: Symbol('STORAGE'),
  DOCUMENT_REPOSITORY: Symbol('DOCUMENT_REPOSITORY'),
  JOB_REPOSITORY: Symbol('JOB_REPOSITORY'),
  ATTEMPT_REPOSITORY: Symbol('ATTEMPT_REPOSITORY'),
  RESULT_REPOSITORY: Symbol('RESULT_REPOSITORY'),
  PAGE_ARTIFACT_REPOSITORY: Symbol('PAGE_ARTIFACT_REPOSITORY'),
  DEAD_LETTER_REPOSITORY: Symbol('DEAD_LETTER_REPOSITORY'),
  AUDIT: Symbol('AUDIT'),
  JOB_PUBLISHER: Symbol('JOB_PUBLISHER'),
  UNIT_OF_WORK: Symbol('UNIT_OF_WORK'),
  EXTRACTION_PIPELINE: Symbol('EXTRACTION_PIPELINE')
} as const;
