export const TOKENS = {
  CLOCK: Symbol('CLOCK'),
  ID_GENERATOR: Symbol('ID_GENERATOR'),
  HASHING: Symbol('HASHING'),
  PAGE_COUNTER: Symbol('PAGE_COUNTER'),
  BINARY_STORAGE: Symbol('BINARY_STORAGE'),
  DOCUMENT_REPOSITORY: Symbol('DOCUMENT_REPOSITORY'),
  JOB_REPOSITORY: Symbol('JOB_REPOSITORY'),
  ATTEMPT_REPOSITORY: Symbol('ATTEMPT_REPOSITORY'),
  RESULT_REPOSITORY: Symbol('RESULT_REPOSITORY'),
  JOB_PUBLISHER: Symbol('JOB_PUBLISHER'),
  AUDIT: Symbol('AUDIT'),
  AUTHORIZATION: Symbol('AUTHORIZATION')
} as const;

