export enum JobStatus {
  RECEIVED = 'RECEIVED',
  VALIDATED = 'VALIDATED',
  STORED = 'STORED',
  PUBLISH_PENDING = 'PUBLISH_PENDING',
  DEDUPLICATED = 'DEDUPLICATED',
  REPROCESSED = 'REPROCESSED',
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  PARTIAL = 'PARTIAL',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED'
}

export enum AttemptStatus {
  PENDING = 'PENDING',
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  PARTIAL = 'PARTIAL',
  FAILED = 'FAILED',
  TIMED_OUT = 'TIMED_OUT',
  MOVED_TO_DLQ = 'MOVED_TO_DLQ'
}

export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  TRANSIENT_FAILURE = 'TRANSIENT_FAILURE',
  FATAL_FAILURE = 'FATAL_FAILURE',
  TIMEOUT = 'TIMEOUT',
  DLQ_ERROR = 'DLQ_ERROR',
  REPROCESSING_ERROR = 'REPROCESSING_ERROR'
}

export enum Role {
  OWNER = 'OWNER',
  OPERATOR = 'OPERATOR'
}

export enum ArtifactType {
  ORIGINAL = 'ORIGINAL',
  RENDERED_IMAGE = 'RENDERED_IMAGE',
  OCR_JSON = 'OCR_JSON',
  MASKED_TEXT = 'MASKED_TEXT',
  LLM_PROMPT = 'LLM_PROMPT',
  LLM_RESPONSE = 'LLM_RESPONSE'
}

export enum QueuePublicationOutboxStatus {
  PENDING = 'PENDING',
  PUBLISHED = 'PUBLISHED'
}
