export enum JobStatus {
  RECEIVED = 'RECEIVED',
  VALIDATED = 'VALIDATED',
  STORED = 'STORED',
  DEDUPLICATED = 'DEDUPLICATED',
  REPROCESSED = 'REPROCESSED',
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  PARTIAL = 'PARTIAL',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED'
}

export enum AttemptStatus {
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED'
}

export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  TRANSIENT_FAILURE = 'TRANSIENT_FAILURE',
  FATAL_FAILURE = 'FATAL_FAILURE',
  TIMEOUT = 'TIMEOUT',
  DLQ_ERROR = 'DLQ_ERROR',
  REPROCESSING_ERROR = 'REPROCESSING_ERROR'
}

export enum Role {
  OWNER = 'OWNER',
  OPERATOR = 'OPERATOR'
}

export enum ArtifactType {
  ORIGINAL = 'ORIGINAL',
  RENDERED_IMAGE = 'RENDERED_IMAGE',
  OCR_JSON = 'OCR_JSON',
  MASKED_TEXT = 'MASKED_TEXT'
}

